# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the rst 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# ! By considering the terms in the Fibonacci sequence whose values do not exceed four
# million, nd the sum of the even-valued terms.

# TODO list of fibonacci numbers until 4 million. Then list of even numbers of that list. Then the sum of that list.

i = 0
fiblist = [1, 2]
while i < 4000000:
    a = fiblist[len(fiblist) - 2]
    b = fiblist[len(fiblist) - 1]
    i = a + b
    if i < 4000000:
        fiblist.append(i)

i = 0
res = 0
evenfiblist = []

while i < len(fiblist):
    res += fiblist[i]
    if fiblist[i] % 2 == 0:
        evenfiblist.append(fiblist[i])
    i += 1

i = 0
evenres = 0

while i < len(evenfiblist):
    evenres += evenfiblist[i]
    i += 1


print(i);
print(fiblist[len(fiblist) - 1])
print(evenres)
print(res)
